### PR TITLE
use jna to compute library version

### PR DESCRIPTION
**Pull request by carstenartur**
use jna to compute library version. Other way does not work for me.

### CODE REVIEW

**Comment by kritzikratzi** [comment]
could you add some comments where the magic numbers from and how to change them if needed?

**Comment by carstenartur** [comment]
They are the Version of the latest Canon dll. You can See it in the dll properties. The difference to the existing Test is only the way to get the Version and Maybe I am using the latest Version.

**Comment by kritzikratzi** [comment]
oh, i meant to the source code, not as a comment :)

**Comment by carstenartur** [comment]
Right, as soon as i am back from vacation in a few days, ok?

**Comment by kritzikratzi** [comment]
enjoy your vacation!

**Comment by carstenartur** [comment]
Hope it is better now. Please feel free to make changes!

**Pull request merged**
